---
title: "homework6_solutions"
author: "Bertrand Wilden"
date: "2/8/2021"
output: html_document
---

```{r message=F}
library(tidyverse)
library(here)
library(tidylog)
```

```{r}
# Read in party codes crosswalk file
parcodes <- read_csv(here("week-7", "data", "parcodes.csv"))

# Read in party ideology data
ideo <- read_csv(here("week-7", "data", "IDEOLOGY.csv")) %>% 
  # Match the party codes with the labels in ideology data
  left_join(parcodes, by = c("PARTY" = "SGLPAR"))

# Read in state codes crosswalk file
states <- read_csv(here("week-7", "data", "STATES.csv"))

# Read in the census demographics data
census <- read_csv(here("week-7", "data", "CENSUS.csv")) %>% 
  # This file is at the munipality level, but we want it to be at the state level
  group_by(UF) %>% # Group by state code
  # Generate a new variable for the proportion of urban inhabitants by state
  summarise(prop_urban = 1 - mean(POPRURAL/POP))

# Read in election level data
# We want a measure of partisanship by state
# I operationalized this as the proportion of party-line votes across elections per state
election <- read_csv(here("week-7", "data", "ELECTION.csv")) %>% 
  # Create an indicator variable for party-line vote
  mutate(party_vote = if_else(NUM_VOTAVEL < 90 & NUM_VOTAVEL >= 10, 1, 0)) %>%
  # Keep only Congressional elections
  filter(COD_CARGO == 7) %>% 
  # Grouping at the state-level
  group_by(SGL_UE) %>% 
  mutate(total_votes = sum(QTD_VOTOS)) %>%  # Computes the sum of all votes per state
  # Now I group by BOTH state and party-line vote indicator
  group_by(SGL_UE, party_vote) %>% 
  # Sum of party votes over total votes gives us the proportion we need
  summarise(partisanship = sum(QTD_VOTOS) / total_votes) %>% 
  ungroup() %>% 
  # Delete rows with non-party vote proportions
  filter(party_vote == 1) %>% 
  select(SGL_UE, partisanship) %>% 
  distinct()
# This method was a bit hacky-ish. Maybe you all came up with a better method?

# Now we need to build our party cohesion variable!
# Read in Congressional votes data
votes <- read_csv(here("week-7", "data", "tallvotes.csv")) %>% 
  # Extract state codes and save as a new variable
  mutate(uf2 = str_sub(DEPNCODE, 4, 5)) %>% 
  # Group by unique bill, party, and state!
  group_by(vnum, DEPPID, uf2) %>% 
  # Calculate a "bill cohesion" measure based on the formula given
  summarise(bill_cohesion = abs(sum(DEPVOTE == 1) - sum(DEPVOTE == 2)) / sum(DEPVOTE)) %>% 
  # Now group by party and state only
  group_by(DEPPID, uf2) %>% 
  # Calculate "party cohesion" by averaging over "bill cohesion" within party-state observations
  summarise(party_cohesion = mean(bill_cohesion, na.rm = T)) %>% 
  # Join ideology at the party level
  left_join(ideo, by = c("DEPPID" = "PARTY")) %>% 
  # Join state crosswalk at the state level
  left_join(states, by = "uf2") %>% 
  # Join census data at the state level with the help of our crosswalk codes
  left_join(census, by = "UF") %>% 
  # Join partisanship data at the state level
  left_join(election, by = c("uf2" = "SGL_UE"))
```

```{r}
summary(lm(party_cohesion ~ IDEOLOGY + prop_urban + partisanship, data = votes))
```

