---
title: "Untitled"
author: "Bertrand Wilden"
date: "1/15/2021"
output: html_document
---

# The Normal PDF



$$
f(x|\mu,\sigma) = \frac{1}{\sqrt{2\pi\sigma^2}}
                                 \text{exp}\left(-\frac{(x-\mu)^2}{2\sigma^2}\right)
$$

$$
f(x|0,1) = \frac{1}{\sqrt{2\pi*1^2}}
                                 \text{exp}\left(-\frac{(x-0)^2}{2*1^2}\right)
$$

```{r}
curve(dnorm, lwd = 2, xlim = c(-4,  4), ylab = "Density", main = "Normal Probability Density Funtion (PDF)")
```

What is the height of the curve at $x = -1$?

```{r}
curve(dnorm, lwd = 2, xlim = c(-4,  4), ylab = "Density", main = "Normal Probability Density Funtion (PDF)")
abline(v = -1, h = dnorm(-1, 0, 1), col = "red", lty = 2)
```

What is the height of the curve at $x = -2$?

```{r}
curve(dnorm, lwd = 2, xlim = c(-4,  4), ylab = "Density", main = "Normal Probability Density Funtion (PDF)")
abline(v = -2, h = dnorm(-2, 0, 1), col = "red", lty = 2)
# segments(x0 = -2, y0 = 0, x1 = -2, y1 = dnorm(-2, 0, 1), col = "red", lty = 2)
# segments(x0 = -5, y0 = dnorm(-2, 0, 1), x1 = -2, y1 = dnorm(-2, 0, 1), col = "red", lty = 2)
```


```{r message=F}
library(dplyr)
data_entry <- tribble(
  ~col_1,   ~col_2,
  1,         23,
  3,         23,
  5,         11,
  6,         1,
  7,         0
)
data_entry
```

The mean of a standard normal draw is: `r mean(rnorm(1000))`