---
title: "homework4_solutions"
author: "Bertrand Wilden"
date: "2/2/2021"
output: html_document
---

```{r message=F}
library(tidyverse)
library(broom)
library(texreg)
```


## Regression to the Mean

```{r}
heights <- read.table("https://raw.githubusercontent.com/avehtari/ROS-Examples/master/PearsonLee/data/MotherDaughterHeights.txt")
head(heights)
```
```{r}
mod <- lm(daughter_height ~ mother_height, data = heights) %>% 
  tidy()

alpha <- round(mod$estimate[1], 2)
beta <- round(mod$estimate[2], 2)
```


```{r}
heights %>%
  ggplot(aes(x = mother_height, y = daughter_height)) +
  geom_point(color = "white") +
  geom_jitter(
    width = 0.5,
    height = 0.5,
    color = "darkcyan",
    alpha = 0.2
  ) +
  geom_smooth(method = "lm", color = "violetred4") +
  annotate(
    geom = "text",
    label = paste("y =", alpha, "+", beta, "* x + e"),
    x = 68,
    y = 55
  ) +
  theme_minimal()
```
What do the parameters of this regression correspond to?

Is this a paradox???


```{r}
n <- 1000

true_ability <- rnorm(n, 50, 10)
noise_1 <- rnorm(n, 0, 10)
noise_2 <- rnorm(n, 0, 10)
midterm <- true_ability + noise_1
final <- true_ability + noise_2

exams <- data.frame(midterm, final)
```

```{r}
lm(final ~ midterm, data = exams) %>% 
  screenreg()
```

```{r}
exams %>% 
  ggplot(aes(x = midterm, y = final)) +
  geom_point(color = "violetred4", alpha = 0.6) +
  geom_smooth(method = "lm", color = "steelblue") +
  theme_minimal()
```
What the f?

## 6

The null distribution
```{r message=F}
N <- 1000

null_results <- rep(NA, N)
for (i in 1:N) {
  x <- rnorm(25)
  e <- rnorm(25)
  a <- 0
  b <- 0
  y <- a + b * x + e
  
  mod <- lm(y ~ x)
  
  RegSS <- sum((augment(mod)$.fitted - mean(y))^2)
  TSS <- sum((y - mean(y))^2)
  
  result <- (RegSS / 1) / (TSS / 23)
  
  null_results[i] <- result
}
```


```{r message=F}
hist(null_results, br = 20, col = "cadetblue", freq = F)
curve(df(x, 1, 23), add = TRUE, lwd = 4, col = "violetred4")
```

```{r}
mod_results <- rep(NA, N)
for (i in 1:N) {
  x <- rnorm(25)
  e <- rnorm(25)
  a <- 0
  b <- 1
  y <- a + b * x + e
  
  mod <- lm(y ~ x)
  
  RegSS <- sum((augment(mod)$.fitted - mean(y))^2)
  TSS <- sum((y - mean(y))^2)
  
  result <- (RegSS / 1) / (TSS / 23)
  
  mod_results[i] <- result
}

hist(mod_results, br = 20, col = "cadetblue", freq = F)
abline(v = mean(mod_results), lwd = 4, lty = 1, col = "gold")
curve(df(x, 1, 23), add = TRUE, lwd = 4, col = "violetred4")
```

